### ISSUE TITLE
Error, dirname must be a directory

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/profiling#56]
Profiling tests pass, but when they are executed with all packages loaded, I am seeing this in the log:
```
Error, dirname must be a directory
Error, dirname must be a directory
Error, dirname must be a directory
Error, dirname must be a directory
Error, dirname must be a directory
Error, dirname must be a directory
Error, dirname must be a directory
Error, dirname must be a directory
```
See e.g. in stable-4.10 GAP branch at https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.10/jobs/430006516. Same happens under the GAP master branch.

**Comment by ChrisJefferson** [comment]
Is really a GAP/IO problem, will be discussed over at https://github.com/gap-system/gap/issues/2827

**Comment by fingolfin** [comment]
@alex-konovalov I believe this has been resolved and can be closed?

**Comment by alex-konovalov** [comment]
I still see these error messages, e.g. in https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/507465849 a day ago.

**Comment by ChrisJefferson** [comment]
We didn't backport the fix to 4.10. I'd prefer to not backport it as it isn't actually required to fix any errors. It doesn't do any harm and (I believe) doesn't make the tests fail.

**Comment by alex-konovalov** [comment]
Ah, ok then (I checked stable-4.10 as it was originally reported there). In this case, closing this as resolved (to check see e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-staging/jobs/508045826 which fails but that was reported in https://github.com/gap-packages/profiling/issues/58 and apparently fixed in the new release, which has been picked up and is awaiting evaluation.
